In [1]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series([1,3,5, np.nan, 6, 8])
print('Passing list of values:',s)

Passing list of values: 0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [7]:
dates = pd.date_range('20130101', periods=6)
print('Adding 6 days with range:',dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print('Passing NumPy array into Pandas:', df)

Adding 6 days with range: DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Passing NumPy array into Pandas:                    A         B         C         D
2013-01-01 -0.684105 -0.446083 -0.193273 -0.218899
2013-01-02  1.701952 -1.578945  1.193032  0.950053
2013-01-03 -0.874834 -0.108115 -2.488084 -2.246679
2013-01-04  0.203930  1.117985 -1.536360  2.046269
2013-01-05 -0.945537 -0.236682  0.150494  0.044839
2013-01-06 -0.476841  0.026294  0.129915 -0.411100


In [10]:
# Creating Data Frame by passing dict objects in series
df2 = pd.DataFrame({'A': 1,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1,index=list(range(4))),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
print('Passing dict of objects :', df2)

# Data Types
print('Data Types:',df2.dtypes)

Passing dict of objects :    A          B  C  D      E    F
0  1 2013-01-02  1  3   test  foo
1  1 2013-01-02  1  3  train  foo
2  1 2013-01-02  1  3   test  foo
3  1 2013-01-02  1  3  train  foo
Data Types: A             int64
B    datetime64[ns]
C             int64
D             int32
E          category
F            object
dtype: object


### Functions
- df2.A                  df2.bool
- df2.abs                df2.boxplot
- df2.add                df2.C
- df2.add_prefix         df2.clip
- df2.add_suffix         df2.columns
- df2.align              df2.copy
- df2.all                df2.count
- df2.any                df2.combine
- df2.append             df2.D
- df2.apply              df2.describe
- df2.applymap           df2.diff
- df2.B                  df2.duplicated

In [23]:
# Viewing Data
print(df.head())
print(df.tail(3))
print(df.index)
print(df.columns)

                   A         B         C         D
2013-01-01 -0.684105 -0.446083 -0.193273 -0.218899
2013-01-02  1.701952 -1.578945  1.193032  0.950053
2013-01-03 -0.874834 -0.108115 -2.488084 -2.246679
2013-01-04  0.203930  1.117985 -1.536360  2.046269
2013-01-05 -0.945537 -0.236682  0.150494  0.044839
                   A         B         C         D
2013-01-04  0.203930  1.117985 -1.536360  2.046269
2013-01-05 -0.945537 -0.236682  0.150494  0.044839
2013-01-06 -0.476841  0.026294  0.129915 -0.411100
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')


In [27]:
# Converting data frame to numpy
print('Data Frame:',df)
print('Converted to NumPy:',df.to_numpy())

Data Frame:                    A         B         C         D
2013-01-01 -0.684105 -0.446083 -0.193273 -0.218899
2013-01-02  1.701952 -1.578945  1.193032  0.950053
2013-01-03 -0.874834 -0.108115 -2.488084 -2.246679
2013-01-04  0.203930  1.117985 -1.536360  2.046269
2013-01-05 -0.945537 -0.236682  0.150494  0.044839
2013-01-06 -0.476841  0.026294  0.129915 -0.411100
Converted to NumPy: [[-0.68410509 -0.44608317 -0.19327349 -0.21889892]
 [ 1.70195206 -1.57894536  1.19303209  0.95005294]
 [-0.87483448 -0.1081146  -2.48808363 -2.2466792 ]
 [ 0.20392989  1.1179845  -1.53635957  2.04626947]
 [-0.94553679 -0.23668174  0.15049407  0.04483873]
 [-0.47684083  0.0262937   0.12991523 -0.41109955]]


In [31]:
# Statistical Summary
print('Summary:',df.describe())
# Transposing data
print('Transpose Data Frame:',df.T)
# Sorting by axis
print('Sort by an axis:',df.sort_index(axis=1, ascending=False))
# Sorting by values
print('Sorting by column B:',df.sort_values(by='B'))

Summary:               A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.179239 -0.204258 -0.457379  0.027414
std    1.009972  0.867182  1.326348  1.438875
min   -0.945537 -1.578945 -2.488084 -2.246679
25%   -0.827152 -0.393733 -1.200588 -0.363049
50%   -0.580473 -0.172398 -0.031679 -0.087030
75%    0.033737 -0.007308  0.145349  0.723749
max    1.701952  1.117985  1.193032  2.046269
Transpose Data Frame:    2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.684105    1.701952   -0.874834    0.203930   -0.945537   -0.476841
B   -0.446083   -1.578945   -0.108115    1.117985   -0.236682    0.026294
C   -0.193273    1.193032   -2.488084   -1.536360    0.150494    0.129915
D   -0.218899    0.950053   -2.246679    2.046269    0.044839   -0.411100
Sort by an axis:                    D         C         B         A
2013-01-01 -0.218899 -0.193273 -0.446083 -0.684105
2013-01-02  0.950053  1.193032 -1.578945  1.701952
2013-01-03 -2.2

In [35]:
# Selection
print('Select a column', df['A'])
# Slicing rows
print('0 to 3 row position:', df[0:3])
print('Sling rows with Index:', df['20130102':'20130104'])
# Selection by label
print('Select based on labels:', df.loc[dates[0]])
print('Select on multi-axis label:', df.loc[:, ['A','B']])


Select a column 2013-01-01   -0.684105
2013-01-02    1.701952
2013-01-03   -0.874834
2013-01-04    0.203930
2013-01-05   -0.945537
2013-01-06   -0.476841
Freq: D, Name: A, dtype: float64
0 to 3 row position:                    A         B         C         D
2013-01-01 -0.684105 -0.446083 -0.193273 -0.218899
2013-01-02  1.701952 -1.578945  1.193032  0.950053
2013-01-03 -0.874834 -0.108115 -2.488084 -2.246679
Sling rows with Index:                    A         B         C         D
2013-01-02  1.701952 -1.578945  1.193032  0.950053
2013-01-03 -0.874834 -0.108115 -2.488084 -2.246679
2013-01-04  0.203930  1.117985 -1.536360  2.046269
Select based on labels: A   -0.684105
B   -0.446083
C   -0.193273
D   -0.218899
Name: 2013-01-01 00:00:00, dtype: float64
Select on multi-axis label:                    A         B
2013-01-01 -0.684105 -0.446083
2013-01-02  1.701952 -1.578945
2013-01-03 -0.874834 -0.108115
2013-01-04  0.203930  1.117985
2013-01-05 -0.945537 -0.236682
2013-01-06 -0.476841  0.0